#docker-compose.yml (Base)
version: '3.4'

networks:
  retronet: 
    driver: bridge     

secrets:
  user_ssh_key:
    file: ./secrets/ssh/id_rsa_shared
  user_ssh_pubkey:
    file: ./secrets/ssh/id_rsa_shared.pub
     
services:
  vde-switch:
    image: retronetsec/vde-switch:${TAG:-latest}
    build: 
      context: ./networking/vde-switch
      secrets: 
        - user_ssh_pubkey
    ports: 
      - "2022:22"
      - "5899:5899"  
    networks:
      - retronet  
    container_name: vde-switch
    stdin_open: true 
    tty: true
    cap_add:
      - NET_ADMIN

  fs1:
    image: retronetsec/fs1:${TAG:-latest}
    build : 
      context: ./networking/FileServer
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
      - vde-switch
    links:
      - vde-switch
    networks:
      - retronet  
    cap_add:
      - mknod
      - NET_ADMIN




  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./networking/dns/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - retronet  

  dos622:
    image: retronetsec/dos622:${TAG:-latest}
    build : ./hosts/DOS/ms-dos-6-22
    ports: 
       - "5910:5900"  

  wfw:
    image: retronetsec/wfw:${TAG:-latest}
    build : 
      context: ./hosts/Windows/Win3.11
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
      - vde-switch
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5901:5900"  

  win95plus:
    image: retronetsec/win95plus:${TAG:-latest}
    build : 
      context: ./hosts/Windows/Win95
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
      - vde-switch
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5906:5900"  



  doomipx:   
    image: retronetsec/doomipx:${TAG:-latest}
    build : 
      context: ./hosts/DOS/DoomIPX
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5902:5900"  


  doomipx2:   
    image: retronetsec/doomipx:${TAG:-latest}
    build : 
      context: ./hosts/DOS/DoomIPX
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5903:5900"  

  ms-dos-6-22-tcpip:   
    image: retronetsec/ms-dos-6-22-tcpip:${TAG:-latest}
    build : 
      context: ./hosts/DOS/ms-dos-6-22-tcpip
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5905:5900"  


  v7x86:   
    image: retronetsec/v7x86:${TAG:-latest}
    build : 
      context: ./hosts/Unix/v7x86
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5907:5900"  

  kali:   
    image: retronetsec/kali:${TAG:-latest}
    build : 
      context: ./hosts/modern/kali
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5922:22"  
    cap_add:
      - NET_ADMIN


  stig:   
    image: retronetsec/stig:${TAG:-latest}
    build : 
      context: ./hosts/DOS/stig
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
        vde-switch:
          condition: service_started
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5904:5900"  

