#docker-compose.yml (Base)
version: '3.4'

networks:
  retronet: 
    driver: bridge     

secrets:
  user_ssh_key:
    file: ./secrets/ssh/id_rsa_shared
  user_ssh_pubkey:
    file: ./secrets/ssh/id_rsa_shared.pub
     
services:
  vde-switch:
    image: retronetsec/vde-switch:${TAG:-latest}
    build: 
      context: ./networking/vde-switch
      secrets: 
        - user_ssh_pubkey
    ports: 
      - "2022:22"
    networks:
      - retronet  
    container_name: vde-switch
    stdin_open: true 
    tty: true
    
  dos611:
    image: retronetsec/dos622:${TAG:-latest}
    build : ./clients/DOS/ms-dos-6-22
    ports: 
       - "5900:5900"  

  wfw:
    image: retronetsec/wfw:${TAG:-latest}
    build : 
      context: ./clients/Windows/Win3.11
      secrets: 
        - user_ssh_key
    environment:
      - vdehost=vde-switch
    depends_on:
      - vde-switch
    links:
      - vde-switch
    networks:
      - retronet  
    ports: 
       - "5901:5900"  

